### ISSUE TITLE
Add a step for adding https binding and requesting/assigning a SSL cert to it.

### ISSUE THREAD

**Issue by gawainXX** [cfloquetprojects/homelab#1]
Greetings, Thank you for this great guide! I did however encounter one snag when enabling CES and kept encountering this error.

```
More data is available. 0x800700ea (WIN32/HTTP: 234 ERROR_MORE_DATA)
```

It looks like in your guide you already had a SSL cert configured for IIS (Perhaps from a previous activity?) However I found that what I needed to do was request and then assign a SSL cert for HTTPS via IIS manager to proceed.

**Comment by cfloquetprojects** [comment]
Hey @gawainXX, thanks very much for the feedback it's sincerely appreciated! Unfortunately I'm not able to tell what article or wiki post you're referring to just based on your comment. I think configuring SSL for IIS is covered in one of the labs I wrote under "Active Directory Certificate Services", so that could be of help if you are still stuck on that. At any rate I'm constantly trying to improve and validate my own documentation so please let me know if you're still spinning your wheels and I'd be glad to lend a hand at trying to fix whatever problem you are having!
